import { WordConversion } from ".";

export const CharacterToKanaConversions: WordConversion[] = [
	{ conversionPattern: { main: "a" }, afterConversion: "エー" },
	{ conversionPattern: { main: "b" }, afterConversion: "ビー" },
	{ conversionPattern: { main: "c" }, afterConversion: "シー" },
	{ conversionPattern: { main: "d" }, afterConversion: "ディー" },
	{ conversionPattern: { main: "e" }, afterConversion: "イー" },
	{ conversionPattern: { main: "f" }, afterConversion: "エフ" },
	{ conversionPattern: { main: "g" }, afterConversion: "ジー" },
	{ conversionPattern: { main: "h" }, afterConversion: "エイチ" },
	{ conversionPattern: { main: "i" }, afterConversion: "アイ" },
	{ conversionPattern: { main: "j" }, afterConversion: "ジェイ" },
	{ conversionPattern: { main: "k" }, afterConversion: "ケー" },
	{ conversionPattern: { main: "l" }, afterConversion: "エル" },
	{ conversionPattern: { main: "m" }, afterConversion: "エム" },
	{ conversionPattern: { main: "n" }, afterConversion: "エヌ" },
	{ conversionPattern: { main: "o" }, afterConversion: "オー" },
	{ conversionPattern: { main: "p" }, afterConversion: "ピー" },
	{ conversionPattern: { main: "q" }, afterConversion: "キュー" },
	{ conversionPattern: { main: "r" }, afterConversion: "アール" },
	{ conversionPattern: { main: "s" }, afterConversion: "エス" },
	{ conversionPattern: { main: "t" }, afterConversion: "ティー" },
	{ conversionPattern: { main: "u" }, afterConversion: "ユー" },
	{ conversionPattern: { main: "v" }, afterConversion: "ヴイー" },
	{ conversionPattern: { main: "w" }, afterConversion: "ダブル" },
	{ conversionPattern: { main: "x" }, afterConversion: "エックス" },
	{ conversionPattern: { main: "y" }, afterConversion: "ワイ" },
	{ conversionPattern: { main: "z" }, afterConversion: "ゼット" },
];
